# Example 6.6: Your model of some physical system results in $N=100$ coupled linear equations with $N$ unknowns: 

$a_{00} y_0 + a_{01} y_1 + ... + a_{0(N-1)} y_{N-1} = b_0$

$a_{10} y_0 + a_{11} y_1 + ... + a_{1(N-1)} y_{N-1} = b_1$

$...$

$a_{(N-1)0} y_0 + a_{(N-1)1} y_1 + ... + a_{(N-1)(N-1)} y_{N-1} = b_{N-1}$

In this example, take the matrix $\mathbf{a}$ to be the Hilbert matrix (see https://en.wikipedia.org/wiki/Hilbert_matrix) and $\mathbf{b}$ its first column:

$\mathbf{a} = \left(\begin{array}{c} 
1 & \frac{1}{2} & \frac{1}{3} & \frac{1}{4} & ... & \frac{1}{100}  \\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \frac{1}{5} & ... & \frac{1}{101} \\
\ddots & \ddots & \ddots & \ddots &  \ddots & \ddots \\
\frac{1}{100} & \frac{1}{101} & \frac{1}{102} & ... & ... & \frac{1}{199}
\end{array}\right)$

or $a_{ij} = \frac{1}{i+j - 1}$.

and $\vec{b} = \left(\begin{array}{c}
1 \\
\frac{1}{2}\\
\frac{1}{3}\\
\ddots\\
\frac{1}{100}\end{array}\right)
$

Solve the matrix equation, $\mathbf{a} \vec{y} = \vec{b}$ numerically, and compare to the analytic solution:
$\vec{y} = \left(\begin{array}{c}
1 \\
0\\
\ddots\\
0\\
\end{array}\right)
$


Solution: 

Let's first construct the 100x100 and 100x1 matrices and then use NumPy's ```linalg``` to get the result!

In [15]:
import numpy as np
from numpy import linalg

# construct the 100x100 Hilbert matrix:
# start with a 100x100 NumPy array: 
a = np.zeros((100,100))
for i in range(100):
    for j in range(100):
        a[i][j] = 1/(i+j+1)

# check output!
print('a=',a)

# now get the vector a as its first column: 
b = a[0][:]
# check:
print('b=',b)

# and use linalg to get the answer!
y = linalg.solve(a,b)
# print: 
print('y=',y)

a= [[1.         0.5        0.33333333 ... 0.01020408 0.01010101 0.01      ]
 [0.5        0.33333333 0.25       ... 0.01010101 0.01       0.00990099]
 [0.33333333 0.25       0.2        ... 0.01       0.00990099 0.00980392]
 ...
 [0.01020408 0.01010101 0.01       ... 0.00512821 0.00510204 0.00507614]
 [0.01010101 0.01       0.00990099 ... 0.00510204 0.00507614 0.00505051]
 [0.01       0.00990099 0.00980392 ... 0.00507614 0.00505051 0.00502513]]
b= [1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
 0.07692308 0.07142857 0.06666667 0.0625     0.05882353 0.05555556
 0.05263158 0.05       0.04761905 0.04545455 0.04347826 0.04166667
 0.04       0.03846154 0.03703704 0.03571429 0.03448276 0.03333333
 0.03225806 0.03125    0.03030303 0.02941176 0.02857143 0.02777778
 0.02702703 0.02631579 0.02564103 0.025      0.02439024 0.02380952
 0.02325581 0.02272727 0.02222222 0.02173913 0.0212766  0.02083333
 0.02040816 0.